name: Another Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: gitboard-io/gitboard-action@main
        with:
          username: chrisbarbour
          environment: dev
          key: ${{ secrets.GITBOARD_USER_API_KEY_2 }}
      - run: echo hello
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: gitboard-io/gitboard-action@main
        with:
          username: chrisbarbour
          environment: dev
          key: test
      - run: notacommand
